# Generated by Django 6.0.5 on 2026-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_workexperience_skills_icon_alter_skills_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='About me'),
            preserve_default=False,
        ),
    ]
