# Generated by Django 6.0.5 on 2026-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('credential_url', models.URLField()),
            ],
        ),
    ]
